language: python
os:
  - linux
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest codecov
# command to run tests
script:
  - pytest --cov-report=xml --cov=pycrostates

after_success:
  - bash <(curl -s https://codecov.io/bash)
