steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_testing.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest pycrostates --junitxml=junit/test-results.xml --cov=pycrostates --cov-report=xml
  displayName: 'pytest'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

- bash: |
    curl -s https://codecov.io/bash
  condition: and(eq(variables['Agent.OS'], 'Linux' ), eq(variables['python.version'], '3.9' ))
  displayName: 'Upload to codecov.io'
